# Generated by Django 5.0.2 on 2024-04-19 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('jshr', models.CharField(max_length=50)),
                ('phone_number', models.CharField(blank=True, default='0', max_length=20)),
            ],
        ),
        migrations.RenameModel(
            old_name='Tokens',
            new_name='Keys',
        ),
        migrations.AlterField(
            model_name='keys',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token', to='main.person'),
        ),
    ]
